name: Fix pr base

on:
  pull_request_target:
    types:
      - opened
      - reopened
    branches:
      - "main"
      - "develop"

permissions:
  pull-requests: write

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_REPO: ${{ github.repository }}
  PR_NUMBER: ${{ github.event.number }}

jobs:
  change-base_branch:
    name: Change base branch
    if: |
      github.base_ref == 'main' && github.head_ref != 'develop'
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh pr edit $PR_NUMBER --base develop
