name: Maintain code quality

env:
  # tool versions
  # renovate: datasource=github-releases depName=denoland/deno
  DENO_VERSION: v1.40.3

on:
  push:
    branches: ["**"]
  pull_request:

permissions: {}

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Deno
        uses: denoland/setup-deno@041b854f97b325bd60e53e9dc2de9cb9f9ac0cba # v1.1.4
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Check lint
        run: deno lint
      - name: Check format
        run: deno fmt --check
