name: Maintain code quality

env:
  # tool versions
  # renovate: datasource=github-releases depName=denoland/deno
  DENO_VERSION: v1.43.2

on:
  push:
    branches: ["**"]
  pull_request:

permissions: {}

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Setup Deno
        uses: denoland/setup-deno@041b854f97b325bd60e53e9dc2de9cb9f9ac0cba # v1.1.4
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Check lint
        run: deno lint
      - name: Check format
        run: deno fmt --check
