name: Maintain code quality

on:
  push:
    branches: ["**"]
  pull_request:

permissions: {}

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Deno
        uses: denoland/setup-deno@0df5d9c641efdff149993c321fc27c11c5df8623 # v1.1.3
        with:
          deno-version: "1.36.0"

      - name: Check lint
        run: deno lint
      - name: Check format
        run: deno fmt --check
